AWSTemplateFormatVersion: "2010-09-09"

Description: JAWS DAYS 2021 Security Group Hands On

Parameters:
  VpcCidrBlock:
    Type: String
    Default: 172.18.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-vpc

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Select
        - 0
        - !Cidr [ !GetAtt VPC.CidrBlock, 6, 8 ]
      MapPublicIpOnLaunch: true # Optional
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-public-subnet-1
      VpcId: !Ref VPC

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Select
        - 1
        - !Cidr [ !GetAtt VPC.CidrBlock, 6, 8 ]
      MapPublicIpOnLaunch: true # Optional
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-public-subnet-2
      VpcId: !Ref VPC

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Select
        - 3
        - !Cidr [ !GetAtt VPC.CidrBlock, 6, 8 ]
      MapPublicIpOnLaunch: false # Optional
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-private-subnet-1
      VpcId: !Ref VPC

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Select
        - 4
        - !Cidr [ !GetAtt VPC.CidrBlock, 6, 8 ]
      MapPublicIpOnLaunch: false # Optional
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-private-subnet-2
      VpcId: !Ref VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-igw
